# Generated by Django 4.1.5 on 2023-01-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                ("apellido_materno", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=8)),
                ("Fecha_nacimiento", models.DateField()),
                ("Fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(max_length=100)),
            ],
        ),
    ]
